### ISSUE TITLE
FAQ "who is on the board of directors" is inaccurate, about page may also be inaccurate

### ISSUE THREAD

**Issue by nazunalika** [resf/resf.org#71]
https://www.resf.org/faq/board-of-directors and https://www.resf.org/about should at least match. Or the FAQ page should link directly to the about page instead. The about page should also be verified for further accuracy and updated to include members who are representing the Rocky Linux project.

**Comment by NeilHanlon** [comment]
Hiya @ressonix  - just a nudge on this, as the website is still incorrect.

Namely, Wale is not on the RESF board, but I am
